### ISSUE TITLE
two packages: where to include

### ISSUE THREAD

**Issue by nikosarcevic** [nikosarcevic/HEP-ASTRO-COSMO#10]
I am not a HEP person so I am struggling with where to include these two resources - suggestions welcome

- [x] https://www.xfitter.org/xFitter/ (I guess in the Fitters section?)
- [x] https://lhapdf.hepforge.org (otters as well or something else?)

**Comment by suchitakulkarni** [comment]
Either the fitter section or create a dedicated PDF section. Fitters section slightly preferred IMHO

**Comment by nikosarcevic** [comment]
> Either the fitter section or create a dedicated PDF section. Fitters section slightly preferred IMHO

I just realized my autocorrect corrected Fitters to otters and I am totally fine with that 😂
Thanks SK for helping out with this!

**Comment by suchitakulkarni** [comment]
LOL! I thought about otters, and I couldn't connect anywhere, I assumed I am missing the point. :D

**Comment by pkoppenb** [comment]
There are fitters of publication output data alike those now in the fitters section, and the fitter you use for extracting your signal, as RooFit. zFit https://github.com/zfit/zfit is in that category. Should I add it to statistics? To fitters? Is it too specialised?

**Comment by nikosarcevic** [comment]
I am not an expert in the field but I would say why not? maybe someone might disagree but id say just pull it

**Comment by nikosarcevic** [comment]
> I would add it to statistics? May be we should rename fitters to 'global fitters'. In that respect HiggsBounds/HiggsSignals etc take the experimental results and 'fit' new models to them. The category suggested by you @pkoppenb is pre results category hence they are more statistics related than fitters in this sense?

ok I will rename fitters to Global fitters
