### ISSUE TITLE
Some neutrino code

### ISSUE THREAD

**Issue by PeterDenton** [nikosarcevic/HEP-ASTRO-COSMO#12]
I have been collecting a list of neutrino related code here: https://peterdenton.github.io/Code/index.html.

**Comment by suchitakulkarni** [comment]
Yes! Been planning to cross correlate to your pages. Need more procrastinating :D Thanks for bringing this up.

**Comment by nikosarcevic** [comment]
amazing! thanks!

**Comment by nikosarcevic** [comment]
@PeterDenton  where can we include neutrinos? should they be under HEP/neutrinos? what do you think

**Comment by suchitakulkarni** [comment]
hi @nikosarcevic just link the page at the very bottom of the list and call that section related lists of tools. For every list give appropriate credit to the maintainer. What say?

**Comment by nikosarcevic** [comment]
sounds good for now
