### ISSUE TITLE
SMEFT tools and others

### ISSUE THREAD

**Issue by jorgetc16** [nikosarcevic/HEP-ASTRO-COSMO#13]
I just created my github account so I don't know exactly how to add things or how anything works actually :). So, here there are a compilation of tools for the Standard Model Effective Field Theory (SMEFT) https://inspirehep.net/literature/1760709 and at https://renatofonseca.net/ one can find 3 mathematica packages (GroupMath, Sym2Int and Susyno) for model building and supersymmetric RGEs.

Cheers

**Comment by jorgetc16** [comment]
Well, I'm not sure... GroupMath, Sym2Int and Susyno are used for model building, the first is a tool for Lie Algebras and permutation groups, the second to generate the most general lagrangian given a set of fields and symmetries and the last calculates de RGEs of the susy model you implement (so maybe alongside Spheno?). 

For the SMEFT tools (there are several) either a new section for EFT could be created, or one should classify them because each one has a different utility (WC Mathcing, RGE calculation, Flavour observables, global fits, etc.).

**Comment by nikosarcevic** [comment]
> Well, I'm not sure... GroupMath, Sym2Int and Susyno are used for model building, the first is a tool for Lie Algebras and permutation groups, the second to generate the most general lagrangian given a set of fields and symmetries and the last calculates de RGEs of the susy model you implement (so maybe alongside Spheno?).
> 
> For the SMEFT tools (there are several) either a new section for EFT could be created, or one should classify them because each one has a different utility (WC Mathcing, RGE calculation, Flavour observables, global fits, etc.).

but should this be in HEP or something General as @bradkav suggested? I will need help on this. @pkoppenb  can also jump in

**Comment by jorgetc16** [comment]
Oh, HEP for sure.

**Comment by nikosarcevic** [comment]
> I just realised that there is another issue "To Include" so somehow this is a duplication of that, I can post it there and close this issue.

for sure. let's converge there.
