### ISSUE TITLE
Include flavio / smelli in HEP global fitters

### ISSUE THREAD

**Issue by MJKirk** [nikosarcevic/HEP-ASTRO-COSMO#42]
flavio - https://flav-io.github.io/
smelli - https://smelli.github.io/

I will turn this into a pull request later when I have time

**Comment by nikosarcevic** [comment]
> flavio - https://flav-io.github.io/
> smelli - https://smelli.github.io/
> 
> I will turn this into a pull request later when I have time

Thanks a bunch!
