### ISSUE TITLE
Add NNPDF fitting code

### ISSUE THREAD

**Issue by scarlehoff** [nikosarcevic/HEP-ASTRO-COSMO#54]
We (meaning the NNPDF collaboration) recently open sourced our PDF fitting code:

https://github.com/NNPDF/nnpdf

The documentation is in: https://docs.nnpdf.science/

As to where to classify it, I guess between xfitter and LHAPDF is the obvious place.

Some other codes (shameless plug):

- PDFFlow: https://github.com/N3PDF/pdfflow, basically a clone of LHAPDF that uses TensorFlow and thus can be used to target GPUs
- MadFlow: https://github.com/N3PDF/madflow an automatic event generator using TensorFlow and which can be used to target GPUs.

I can open a PR with all that if it is easier that way.

**Comment by nikosarcevic** [comment]
> We (meaning the NNPDF collaboration) recently open sourced our PDF fitting code:
> 
> https://github.com/NNPDF/nnpdf
> 
> The documentation is in: https://docs.nnpdf.science/
> 
> As to where to classify it, I guess between xfitter and LHAPDF is the obvious place.
> 
> Some other codes (shameless plug):
> 
> * PDFFlow: https://github.com/N3PDF/pdfflow, basically a clone of LHAPDF that uses TensorFlow and thus can be used to target GPUs
> * MadFlow: https://github.com/N3PDF/madflow an automatic event generator using TensorFlow and which can be used to target GPUs.
> 
> I can open a PR with all that if it is easier that way.

yes please if you can do a PR that would be great
