### ISSUE TITLE
wrong url for Monte Python

### ISSUE THREAD

**Issue by lesgourg** [nikosarcevic/HEP-ASTRO-COSMO#66]
Hi, thanks for the nice work!
I just noticed that for Monte Python you have put the obsolete GitHub URL of MontePython (until 2017 and v2.2): https://github.com/baudren/montepython_public/wiki
The GitHub URL of MontePython (since 2018 and v3.0) is: 
https://github.com/brinckmann/montepython_public
Please do the substitution. The old URL is not maintained since 2017. 
Julien Lesgourgues

**Comment by nikosarcevic** [comment]
> Hi, thanks for the nice work!
> I just noticed that for Monte Python you have put the obsolete GitHub URL of MontePython (until 2017 and v2.2): https://github.com/baudren/montepython_public/wiki
> The GitHub URL of MontePython (since 2018 and v3.0) is:
> https://github.com/brinckmann/montepython_public
> Please do the substitution. The old URL is not maintained since 2017.
> Julien Lesgourgues

Dear Julien,

thank you for the kind words and for correcting. The change will be made now.
I am also planning on transporting all of this to a proper website over the xmas break so keep an eye on this.

Also, if you have any master students or PhDs that would like to join the effort -- send them my way.

All the best
Niko and Matthijs

**Comment by lonbar** [comment]
Thanks for bringing this to our attention. I've updated the link in commit 34cb268.
